/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
static yyconst short int yy_accept[228] =
    {   0,
        0,    0,   48,   46,   44,   45,   46,   43,   41,   42,
       36,   34,   39,   35,   37,   32,   40,   38,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,    0,
        0,    0,    0,    0,    0,    0,   33,    0,    0,    0,
        0,    0,    0,   43,   43,   43,   43,   43,   43,   43,
       32,   32,    0,   32,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   15,
       30,   30,   30,   30,   30,   30,   30,   30,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   43,   43,   43,   43,   43,

       43,   43,   31,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,    2,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,    0,   26,   25,
       24,   28,   29,   27,   22,    0,   26,   26,   25,   25,
       24,   24,   28,   28,   29,   29,   27,   27,   22,   22,
       43,   26,   25,   24,   28,   29,   27,   22,   30,   26,
       25,   24,   28,   29,   27,   22,    3,   30,   30,   30,
       17,   30,   30,    5,   30,   30,   30,   30,   30,   13,
        7,   30,   16,   11,   30,   23,   23,   23,   23,   23,
       30,   30,   30,   20,   18,   30,   12,   30,   30,   30,

       30,   14,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   19,   30,    6,    9,    1,    4,   30,   30,
       30,    8,   10,   30,   30,   21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,    1,
       16,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   18,   18,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   18,   18,   18,
        1,    1,    1,    1,    1,    1,   18,   18,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[255] =
    {   0,
        0,    0,  611,   21,    0,  612,   47,   60,    0,    0,
        0,  596,    0,  595,    0,   27,    0,    0,   73,   86,
       28,   41,   31,   63,   37,   39,   76,   87,   89,  580,
      576,   25,   58,  585,  573,  600,  612,   56,   91,  104,
      112,  113,   94,    0,  575,  571,   97,  102,  580,  568,
      585,  115,  584,  116,    0,  569,  565,  103,  111,  574,
      562,  113,  576,  565,  103,  121,  123,  556,  121,    0,
      127,  127,  561,  134,    8,  568,  553,  562,  566,    0,
        0,    0,    0,    0,    0,    0,   58,  149,  153,  159,
      163,  165,  167,  169,  565,    0,    0,    0,    0,    0,

        0,    0,  570,  563,  173,  210,  247,  284,  321,  358,
      395,  556,  549,  559,  555,  557,  413,  552,  543,  554,
      549,  550,  138,  538,  543,  549,  535,    0,  612,  612,
      612,  612,  612,  612,  612,  431,  564,  612,  563,  612,
      562,  612,  561,  612,  560,  612,  559,  612,  558,  612,
        0,    0,    0,    0,    0,    0,    0,    0,  445,    0,
        0,    0,    0,    0,    0,    0,    0,  544,  531,  528,
        0,  521,  525,    0,  508,  520,  515,  516,  500,    0,
        0,  483,    0,    0,  484,  612,  498,  612,    0,    0,
      480,  463,  467,    0,    0,  473,    0,  466,  431,  427,

      415,    0,  408,  416,  419,  413,  405,  410,  371,  340,
      303,  258,    0,  229,    0,    0,    0,    0,  181,  148,
      132,    0,    0,  101,   61,    0,  612,  482,  485,   71,
      488,  491,  494,  497,  500,  503,  506,  509,  512,  515,
      518,  521,  524,  527,  530,  533,  536,  539,  542,  545,
      548,  551,  554,  557
    } ;

static yyconst short int yy_def[255] =
    {   0,
      227,    1,  227,  227,    4,  227,  228,  229,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,  230,  230,
       20,   20,   20,   20,   20,   20,   20,   20,   20,  227,
      227,  227,  227,  227,  227,  228,  227,  228,  228,  228,
      228,  228,  228,  229,  229,  229,  229,  229,  229,  229,
      227,  227,  227,  227,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  227,  231,
      232,  233,  234,  235,  236,  237,  228,  238,  239,  240,
      241,  242,  243,  244,  229,  245,  246,  247,  248,  249,

      250,  251,  227,  230,  227,  227,  227,  227,  227,  227,
      227,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  252,  227,  227,
      227,  227,  227,  227,  227,  253,  228,  227,  228,  227,
      228,  227,  228,  227,  228,  227,  228,  227,  228,  227,
      254,  229,  229,  229,  229,  229,  229,  229,  227,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  227,  228,  227,  229,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,    0,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227
    } ;

static yyconst short int yy_nxt[650] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,    4,   15,   16,   17,   18,   19,   19,   20,   21,
       22,   23,   19,   19,   24,   25,   19,   19,   19,   26,
       19,   27,   19,   28,   19,   19,   29,   30,   53,  111,
       54,   31,  124,   32,   56,   81,   33,   69,   34,   35,
       37,   55,   64,   56,   55,   56,   65,   56,   82,   37,
       55,   37,   55,   38,   55,   72,   66,   39,   67,   40,
       73,   68,   41,   55,   42,   43,   45,  136,   83,   56,
       46,  226,   47,   87,   70,   48,   55,   49,   50,   56,
       71,   84,   56,   57,   37,   58,   74,   37,   59,   55,

       60,   61,   62,   56,   75,   56,   57,   37,   58,   63,
       76,   59,   55,   60,   61,   37,   37,   97,   77,  225,
       78,   88,   99,  106,   89,   94,   53,   53,   52,   54,
       98,  108,   91,   93,  111,  100,  107,   90,  112,  115,
      104,  108,  117,  110,  109,   92,  119,  110,  104,  121,
      123,   36,  138,  116,  109,   36,  140,  180,  111,  224,
      120,   36,  142,  181,  105,   36,  144,   36,  146,   36,
      148,   36,  150,  129,  129,  223,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  160,  129,  129,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,

      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      130,  130,  222,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  161,  130,  130,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  131,  131,  221,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      162,  131,  131,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  132,  132,  220,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  163,  132,  132,

      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  133,  133,  219,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  164,  133,  133,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  134,  134,
      218,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  165,  134,  134,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  135,  135,  217,  135,  135,

      135,  135,  135,  135,  135,  135,  135,  135,  166,  135,
      135,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  172,   36,  188,  216,  215,  173,  214,  213,
      212,  211,  210,  209,  174,  186,  186,  208,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  190,  186,
      186,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,   36,   36,   36,   44,  207,   44,  129,  206,
      129,  130,  205,  130,  131,  204,  131,  132,  203,  132,

      133,   37,  133,  134,  202,  134,  135,  201,  135,  137,
      137,  137,  139,  139,  139,  141,  141,  141,  143,  143,
      143,  145,  145,  145,  147,  147,  147,  149,  149,  149,
      152,  200,  152,  153,  199,  153,  154,  198,  154,  155,
      197,  155,  156,  196,  156,  157,  195,  157,  158,  194,
      158,  186,  193,  186,  187,  187,  187,  189,  192,  189,
      191,   37,   37,   37,   37,   37,   37,   37,  185,  184,
      183,  182,  179,  178,  177,  176,  175,  171,  170,  169,
      168,  167,  159,  103,  151,  128,  127,  126,  125,  122,
      118,  114,  113,  111,  110,  105,  104,  103,   51,  102,

      101,   96,   95,   37,   86,   85,   80,   79,   52,   51,
      227,    3,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227
    } ;

static yyconst short int yy_chk[650] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,   16,   75,
       16,    4,   75,    4,   21,   32,    4,   23,    4,    4,
        7,   21,   21,   25,   23,   26,   21,   22,   32,   38,
       25,   87,   26,    7,   22,   25,   22,    7,   22,    7,
       26,   22,    7,  230,    7,    7,    8,   87,   33,   24,
        8,  225,    8,   38,   24,    8,   24,    8,    8,   19,
       24,   33,   27,   19,   39,   19,   27,   43,   19,   27,

       19,   19,   20,   28,   27,   29,   20,   40,   20,   20,
       28,   20,   29,   20,   20,   41,   42,   47,   28,  224,
       29,   39,   48,   58,   40,   43,   52,   54,   52,   54,
       47,   59,   41,   42,   65,   48,   58,   40,   62,   65,
       62,   66,   67,   67,   59,   41,   69,   71,   69,   72,
       74,   88,   88,   66,   66,   89,   89,  123,   72,  221,
       71,   90,   90,  123,   74,   91,   91,   92,   92,   93,
       93,   94,   94,  105,  105,  220,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,

      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      106,  106,  219,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  107,  107,  214,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  108,  108,  212,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,

      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  109,  109,  211,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  110,  110,
      210,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  111,  111,  209,  111,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  117,  136,  136,  208,  207,  117,  206,  205,
      204,  203,  201,  200,  117,  159,  159,  199,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  228,  228,  228,  229,  198,  229,  231,  196,
      231,  232,  193,  232,  233,  192,  233,  234,  191,  234,

      235,  187,  235,  236,  185,  236,  237,  182,  237,  238,
      238,  238,  239,  239,  239,  240,  240,  240,  241,  241,
      241,  242,  242,  242,  243,  243,  243,  244,  244,  244,
      245,  179,  245,  246,  178,  246,  247,  177,  247,  248,
      176,  248,  249,  175,  249,  250,  173,  250,  251,  172,
      251,  252,  170,  252,  253,  253,  253,  254,  169,  254,
      168,  149,  147,  145,  143,  141,  139,  137,  127,  126,
      125,  124,  122,  121,  120,  119,  118,  116,  115,  114,
      113,  112,  104,  103,   95,   79,   78,   77,   76,   73,
       68,   64,   63,   61,   60,   57,   56,   53,   51,   50,

       49,   46,   45,   36,   35,   34,   31,   30,   14,   12,
        3,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
   #include "synta.tab.h"
   #include "ts.h"
   #include <string.h>
   extern YYSTYPE yylval;
   extern int nb_ligne;
   extern int nb_colonne;
#line 591 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 17 "lex.l"


#line 745 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 228 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 612 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_program;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_end;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_call;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_routine;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng; return mc_endr;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng; return integer;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return real; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng; return character;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0,1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return logical;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return dimension;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng; return mc_true;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_false;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); printf("READ");yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return READ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_write;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return inst_if;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return inst_then;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_else;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_endif;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return inst_dowhile;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_enddo;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_equivalence;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_or;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_and;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 1);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_gt;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0,1); yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_ge;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0,1); yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_eq;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 49 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_ne;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 50 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return mc_le;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 1); yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng; return mc_lt;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "lex.l"
{
    rechercher(yytext,"IDF"," ",0,0,0,0);
    if (yyleng <= 10) {
        yylval.str=strdup(yytext);
        nb_colonne =nb_colonne+ yyleng;return idf;
    } else {
        yylval.str=strdup(yytext);
        printf("\n****WARNING:idf trop long****\n");return idf;
    }
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "lex.l"
{rechercher(yytext,"Cst entiere","REAL",atof(yytext),0,0,0); yylval.reel=atoi(yytext);nb_colonne =nb_colonne+ yyleng; if (atoi(yytext) > 32767.32767 || atoi(yytext) < -32768.32767) {printf("\n***lex.l \"ex1.txt\" ligne %d colonne %d :depasser taille entier***\n", nb_ligne,nb_colonne);} return cst_reel;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "lex.l"
{rechercher(yytext,"Cst entiere","INTEGER",atof(yytext),0,0,0); yylval.entier=atoi(yytext);nb_colonne =nb_colonne+ yyleng; if (atoi(yytext) > 32767 || atoi(yytext) < -32768) {printf("\n***lex.l \"ex1.txt\" ligne %d colonne %d :depasser taille reel***\n", nb_ligne,nb_colonne);} return cst_int;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "lex.l"
{rechercher(yytext,"chaine de car",0,0,0,0, 1); yylval.reel=atoi(yytext);return DOUBL_QUOT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 2); yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return plus;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return moins;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_mult;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return mc_div;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return egal;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return vg;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "lex.l"
{ rechercher(yytext,"Mot cle",0,0, 0,0,2);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return pvg;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "lex.l"
{ rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext); nb_colonne =nb_colonne+ yyleng;return pr_ov;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "lex.l"
{rechercher(yytext,"Mot cle",0,0,0,0, 2);yylval.str=strdup(yytext);nb_colonne =nb_colonne+ yyleng;return pr_fer;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "lex.l"
{rechercher(yytext,"comment",0,0,0,0, 1); nb_colonne =nb_colonne+ yyleng;return comment;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "lex.l"

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "lex.l"
{ nb_ligne++; nb_colonne = 1; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "lex.l"
{ printf("\n***lex.l \"ex1.txt\" ligne %d colonne %d : syntax error***\n", nb_ligne,nb_colonne); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "lex.l"
ECHO;
	YY_BREAK
#line 1072 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 228 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 228 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 227);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 83 "lex.l"


int yywrap() {
    // Handle end-of-file conditions here if needed
    return 1; // Return 1 to indicate no more input
}


